# Generated by Django 3.2.4 on 2021-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_appoinment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(to='hospital.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ManyToManyField(to='hospital.Patient'),
        ),
    ]
