# Generated by Django 3.2.4 on 2021-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='diseaseName',
            field=models.CharField(default='No Disease', max_length=40, unique=True),
        ),
    ]
